// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: pilab/pivirtd/v1/resource_service.proto

package pivirtdv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PivirtdResourceService_ApplyResource_FullMethodName  = "/pilab.pivirtd.v1.PivirtdResourceService/ApplyResource"
	PivirtdResourceService_ApplyResources_FullMethodName = "/pilab.pivirtd.v1.PivirtdResourceService/ApplyResources"
	PivirtdResourceService_GetResource_FullMethodName    = "/pilab.pivirtd.v1.PivirtdResourceService/GetResource"
	PivirtdResourceService_ListResources_FullMethodName  = "/pilab.pivirtd.v1.PivirtdResourceService/ListResources"
	PivirtdResourceService_DeleteResource_FullMethodName = "/pilab.pivirtd.v1.PivirtdResourceService/DeleteResource"
	PivirtdResourceService_ListKinds_FullMethodName      = "/pilab.pivirtd.v1.PivirtdResourceService/ListKinds"
)

// PivirtdResourceServiceClient is the client API for PivirtdResourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PivirtdResourceService is the generic, kind-agnostic resource surface for
// pivirtd. Every registered kind can be applied, fetched, listed and deleted
// through these RPCs, removing the need for per-kind CLI code or agent
// reimplementations.
//
// The same RPC surface is exposed on the agent and the director — the tiers
// differ only in which kinds are registered. See
// node-resource-apply.md §2.3.
type PivirtdResourceServiceClient interface {
	// ApplyResource runs the full admission chain (decode, admit, validate,
	// interlock, diff, persist) for a single resource. The response carries
	// an ApplyResult with the outcome (created, updated, unchanged) and the
	// post-apply resource.
	ApplyResource(ctx context.Context, in *ApplyResourceRequest, opts ...grpc.CallOption) (*ApplyResourceResponse, error)
	// ApplyResources applies multiple resources in kind-dependency order.
	// One failing object does not abort the rest; every object gets a
	// per-object outcome in the response. Dry-run on the batch applies
	// the same flag to every object.
	ApplyResources(ctx context.Context, in *ApplyResourcesRequest, opts ...grpc.CallOption) (*ApplyResourcesResponse, error)
	// GetResource retrieves a single resource by kind and name.
	GetResource(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*GetResourceResponse, error)
	// ListResources returns all resources of a given kind, filtered
	// by an optional label selector matching pkg/resource.Selector
	// semantics (equality, set membership, existence).
	ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error)
	// DeleteResource removes a resource by kind and name. If the resource
	// owns other resources via ownerRefs, the owned resources are deleted
	// first (cascade). Deletion is refused when a child sets
	// blockOwnerDeletion.
	DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*DeleteResourceResponse, error)
	// ListKinds returns the set of resource kinds this tier has registered.
	// This makes the per-tier kind set introspectable, allowing a single
	// CLI binary to talk to either pivirtd or the agent without a
	// build-time table.
	ListKinds(ctx context.Context, in *ListKindsRequest, opts ...grpc.CallOption) (*ListKindsResponse, error)
}

type pivirtdResourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPivirtdResourceServiceClient(cc grpc.ClientConnInterface) PivirtdResourceServiceClient {
	return &pivirtdResourceServiceClient{cc}
}

func (c *pivirtdResourceServiceClient) ApplyResource(ctx context.Context, in *ApplyResourceRequest, opts ...grpc.CallOption) (*ApplyResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyResourceResponse)
	err := c.cc.Invoke(ctx, PivirtdResourceService_ApplyResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pivirtdResourceServiceClient) ApplyResources(ctx context.Context, in *ApplyResourcesRequest, opts ...grpc.CallOption) (*ApplyResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyResourcesResponse)
	err := c.cc.Invoke(ctx, PivirtdResourceService_ApplyResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pivirtdResourceServiceClient) GetResource(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*GetResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResourceResponse)
	err := c.cc.Invoke(ctx, PivirtdResourceService_GetResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pivirtdResourceServiceClient) ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResourcesResponse)
	err := c.cc.Invoke(ctx, PivirtdResourceService_ListResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pivirtdResourceServiceClient) DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*DeleteResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResourceResponse)
	err := c.cc.Invoke(ctx, PivirtdResourceService_DeleteResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pivirtdResourceServiceClient) ListKinds(ctx context.Context, in *ListKindsRequest, opts ...grpc.CallOption) (*ListKindsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKindsResponse)
	err := c.cc.Invoke(ctx, PivirtdResourceService_ListKinds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PivirtdResourceServiceServer is the server API for PivirtdResourceService service.
// All implementations must embed UnimplementedPivirtdResourceServiceServer
// for forward compatibility.
//
// PivirtdResourceService is the generic, kind-agnostic resource surface for
// pivirtd. Every registered kind can be applied, fetched, listed and deleted
// through these RPCs, removing the need for per-kind CLI code or agent
// reimplementations.
//
// The same RPC surface is exposed on the agent and the director — the tiers
// differ only in which kinds are registered. See
// node-resource-apply.md §2.3.
type PivirtdResourceServiceServer interface {
	// ApplyResource runs the full admission chain (decode, admit, validate,
	// interlock, diff, persist) for a single resource. The response carries
	// an ApplyResult with the outcome (created, updated, unchanged) and the
	// post-apply resource.
	ApplyResource(context.Context, *ApplyResourceRequest) (*ApplyResourceResponse, error)
	// ApplyResources applies multiple resources in kind-dependency order.
	// One failing object does not abort the rest; every object gets a
	// per-object outcome in the response. Dry-run on the batch applies
	// the same flag to every object.
	ApplyResources(context.Context, *ApplyResourcesRequest) (*ApplyResourcesResponse, error)
	// GetResource retrieves a single resource by kind and name.
	GetResource(context.Context, *GetResourceRequest) (*GetResourceResponse, error)
	// ListResources returns all resources of a given kind, filtered
	// by an optional label selector matching pkg/resource.Selector
	// semantics (equality, set membership, existence).
	ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error)
	// DeleteResource removes a resource by kind and name. If the resource
	// owns other resources via ownerRefs, the owned resources are deleted
	// first (cascade). Deletion is refused when a child sets
	// blockOwnerDeletion.
	DeleteResource(context.Context, *DeleteResourceRequest) (*DeleteResourceResponse, error)
	// ListKinds returns the set of resource kinds this tier has registered.
	// This makes the per-tier kind set introspectable, allowing a single
	// CLI binary to talk to either pivirtd or the agent without a
	// build-time table.
	ListKinds(context.Context, *ListKindsRequest) (*ListKindsResponse, error)
	mustEmbedUnimplementedPivirtdResourceServiceServer()
}

// UnimplementedPivirtdResourceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPivirtdResourceServiceServer struct{}

func (UnimplementedPivirtdResourceServiceServer) ApplyResource(context.Context, *ApplyResourceRequest) (*ApplyResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyResource not implemented")
}
func (UnimplementedPivirtdResourceServiceServer) ApplyResources(context.Context, *ApplyResourcesRequest) (*ApplyResourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyResources not implemented")
}
func (UnimplementedPivirtdResourceServiceServer) GetResource(context.Context, *GetResourceRequest) (*GetResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResource not implemented")
}
func (UnimplementedPivirtdResourceServiceServer) ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListResources not implemented")
}
func (UnimplementedPivirtdResourceServiceServer) DeleteResource(context.Context, *DeleteResourceRequest) (*DeleteResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteResource not implemented")
}
func (UnimplementedPivirtdResourceServiceServer) ListKinds(context.Context, *ListKindsRequest) (*ListKindsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListKinds not implemented")
}
func (UnimplementedPivirtdResourceServiceServer) mustEmbedUnimplementedPivirtdResourceServiceServer() {
}
func (UnimplementedPivirtdResourceServiceServer) testEmbeddedByValue() {}

// UnsafePivirtdResourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PivirtdResourceServiceServer will
// result in compilation errors.
type UnsafePivirtdResourceServiceServer interface {
	mustEmbedUnimplementedPivirtdResourceServiceServer()
}

func RegisterPivirtdResourceServiceServer(s grpc.ServiceRegistrar, srv PivirtdResourceServiceServer) {
	// If the following call panics, it indicates UnimplementedPivirtdResourceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PivirtdResourceService_ServiceDesc, srv)
}

func _PivirtdResourceService_ApplyResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PivirtdResourceServiceServer).ApplyResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PivirtdResourceService_ApplyResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PivirtdResourceServiceServer).ApplyResource(ctx, req.(*ApplyResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PivirtdResourceService_ApplyResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PivirtdResourceServiceServer).ApplyResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PivirtdResourceService_ApplyResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PivirtdResourceServiceServer).ApplyResources(ctx, req.(*ApplyResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PivirtdResourceService_GetResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PivirtdResourceServiceServer).GetResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PivirtdResourceService_GetResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PivirtdResourceServiceServer).GetResource(ctx, req.(*GetResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PivirtdResourceService_ListResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PivirtdResourceServiceServer).ListResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PivirtdResourceService_ListResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PivirtdResourceServiceServer).ListResources(ctx, req.(*ListResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PivirtdResourceService_DeleteResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PivirtdResourceServiceServer).DeleteResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PivirtdResourceService_DeleteResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PivirtdResourceServiceServer).DeleteResource(ctx, req.(*DeleteResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PivirtdResourceService_ListKinds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKindsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PivirtdResourceServiceServer).ListKinds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PivirtdResourceService_ListKinds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PivirtdResourceServiceServer).ListKinds(ctx, req.(*ListKindsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PivirtdResourceService_ServiceDesc is the grpc.ServiceDesc for PivirtdResourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PivirtdResourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pilab.pivirtd.v1.PivirtdResourceService",
	HandlerType: (*PivirtdResourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyResource",
			Handler:    _PivirtdResourceService_ApplyResource_Handler,
		},
		{
			MethodName: "ApplyResources",
			Handler:    _PivirtdResourceService_ApplyResources_Handler,
		},
		{
			MethodName: "GetResource",
			Handler:    _PivirtdResourceService_GetResource_Handler,
		},
		{
			MethodName: "ListResources",
			Handler:    _PivirtdResourceService_ListResources_Handler,
		},
		{
			MethodName: "DeleteResource",
			Handler:    _PivirtdResourceService_DeleteResource_Handler,
		},
		{
			MethodName: "ListKinds",
			Handler:    _PivirtdResourceService_ListKinds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pilab/pivirtd/v1/resource_service.proto",
}
