// Package director provides distributed task orchestration and agent coordination.
// NodeService is the PIVIRT-83 (control-plane consolidation, Phase 2) session
// stream: one bidirectional stream per node, replacing
// director/v1.CloudDirectorService.AgentEvents and (eventually, Phase 5)
// TaskService.Subscribe. A node's identity is a director-minted UUID bound
// to its mTLS client certificate, never a client-supplied claim.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: pilab/director/v2/node_service.proto

package directorv2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_Register_FullMethodName           = "/pilab.director.v2.NodeService/Register"
	NodeService_RequestCertificate_FullMethodName = "/pilab.director.v2.NodeService/RequestCertificate"
	NodeService_Session_FullMethodName            = "/pilab.director.v2.NodeService/Session"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeServiceClient interface {
	// Register establishes (first join) or re-establishes (reconnect) a
	// node's identity with the director. On first join, called without an
	// mTLS client certificate yet -- authenticated instead by
	// bootstrap_token -- and the director mints a new node_uuid. On
	// reconnect, the caller's mTLS peer identity must already be bound to
	// the supplied node_uuid.
	Register(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	// RequestCertificate submits a CSR for the node_uuid minted by Register
	// and returns a signed mTLS client certificate whose SAN the director
	// asserts itself (spiffe://pilab.hu/node/<node_uuid>), regardless of
	// what the CSR itself claims. Like Register, usable without an existing
	// client certificate via bootstrap_token; a node_uuid may only be
	// certified once (rejects if already bound to a peer identity).
	RequestCertificate(ctx context.Context, in *RequestCertificateRequest, opts ...grpc.CallOption) (*RequestCertificateResponse, error)
	// Session is the node's single long-lived stream to the director. It
	// requires a verified mTLS client certificate -- there is no
	// bootstrap-token path here. The first NodeEvent on the stream must
	// carry the node's current node_uuid and lease_epoch; events from a
	// stale epoch (an older Register than the one currently on record) are
	// dropped, which is what makes a duplicate or restarted agent process
	// safe.
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeEvent, NodeDirective], error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) Register(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, NodeService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) RequestCertificate(ctx context.Context, in *RequestCertificateRequest, opts ...grpc.CallOption) (*RequestCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestCertificateResponse)
	err := c.cc.Invoke(ctx, NodeService_RequestCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeEvent, NodeDirective], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[0], NodeService_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NodeEvent, NodeDirective]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_SessionClient = grpc.BidiStreamingClient[NodeEvent, NodeDirective]

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
type NodeServiceServer interface {
	// Register establishes (first join) or re-establishes (reconnect) a
	// node's identity with the director. On first join, called without an
	// mTLS client certificate yet -- authenticated instead by
	// bootstrap_token -- and the director mints a new node_uuid. On
	// reconnect, the caller's mTLS peer identity must already be bound to
	// the supplied node_uuid.
	Register(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	// RequestCertificate submits a CSR for the node_uuid minted by Register
	// and returns a signed mTLS client certificate whose SAN the director
	// asserts itself (spiffe://pilab.hu/node/<node_uuid>), regardless of
	// what the CSR itself claims. Like Register, usable without an existing
	// client certificate via bootstrap_token; a node_uuid may only be
	// certified once (rejects if already bound to a peer identity).
	RequestCertificate(context.Context, *RequestCertificateRequest) (*RequestCertificateResponse, error)
	// Session is the node's single long-lived stream to the director. It
	// requires a verified mTLS client certificate -- there is no
	// bootstrap-token path here. The first NodeEvent on the stream must
	// carry the node's current node_uuid and lease_epoch; events from a
	// stale epoch (an older Register than the one currently on record) are
	// dropped, which is what makes a duplicate or restarted agent process
	// safe.
	Session(grpc.BidiStreamingServer[NodeEvent, NodeDirective]) error
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) Register(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedNodeServiceServer) RequestCertificate(context.Context, *RequestCertificateRequest) (*RequestCertificateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestCertificate not implemented")
}
func (UnimplementedNodeServiceServer) Session(grpc.BidiStreamingServer[NodeEvent, NodeDirective]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Register(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_RequestCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RequestCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_RequestCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RequestCertificate(ctx, req.(*RequestCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeServiceServer).Session(&grpc.GenericServerStream[NodeEvent, NodeDirective]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_SessionServer = grpc.BidiStreamingServer[NodeEvent, NodeDirective]

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pilab.director.v2.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _NodeService_Register_Handler,
		},
		{
			MethodName: "RequestCertificate",
			Handler:    _NodeService_RequestCertificate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _NodeService_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pilab/director/v2/node_service.proto",
}
